foreground = yes

[cass1]
client = yes
accept = 127.0.0.1:15005
connect = svc1.demo.local:9092

; send SNI
sni = svc1.demo.local

; verify the gateway cert (works with your self-signed cert used as CA)
verifyChain = yes
CAfile = /Users/outlander/workDir/study/18k8s/09EKS-istio/svc1.crt
checkHost = svc1.demo.local