foreground = yes

[cass1]
client = yes
accept = 127.0.0.1:25005
connect = svc2.demo.local:9092

; send SNI
sni = svc2.demo.local

; verify the gateway cert (works with your self-signed cert used as CA)
verifyChain = yes
CAfile = /Users/outlander/workDir/study/18k8s/09EKS-istio/svc2.crt
checkHost = svc2.demo.local